#!/bin/bash
# set -euo pipefail
set -x

export PASS=${PASS:=root}
echo "root:$PASS" | chpasswd

if ! [ -e "/etc/dropbear/dropbear_ecdsa_host_key" ]; then
  dropbearkey -t ecdsa -f /etc/dropbear/dropbear_ecdsa_host_key
fi

openvpn --config /etc/vpn.ht.ovpn &
VPN_PID=$!

dropbear -E -F &
DB_PID=$!

sleep infinity
